# Generated by Django 5.1.3 on 2024-11-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmission',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
