# Generated by Django 5.1.3 on 2024-11-17 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usersubmission_transaction_reference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentVerification',
        ),
    ]
