# Generated by Django 5.1.3 on 2024-11-17 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_paymentverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedTransactionReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('user_submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_record', to='api.usersubmission')),
            ],
            options={
                'ordering': ['-used_at'],
            },
        ),
    ]
